/**
 * Writes a LOCAL-ONLY .env.local that configures the onboarding backend with
 * the filesystem store, so the configured smoke phase and a configured QA
 * pass can run on a developer machine. Never use these values in production.
 *
 *   node scripts/local-env.mjs            # writes .env.local, prints the code + token
 *   node scripts/local-env.mjs --remove   # deletes .env.local
 *
 * .env.local is gitignored. The dev server reloads env files on change.
 */
import { randomBytes, createHash } from "node:crypto";
import { writeFileSync, existsSync, unlinkSync, mkdirSync } from "node:fs";

if (process.argv.includes("--remove")) {
  if (existsSync(".env.local")) unlinkSync(".env.local");
  console.log("removed .env.local");
  process.exit(0);
}

const code = "SOLIDIFY-LOCAL-" + randomBytes(4).toString("hex").toUpperCase();
const token = randomBytes(24).toString("base64url");
const key = randomBytes(32).toString("base64");
const secret = randomBytes(32).toString("base64");
const hash = createHash("sha256").update(code).digest("hex");
mkdirSync(".data/onboarding", { recursive: true });

const env = `# LOCAL ONLY — generated by scripts/local-env.mjs. Never deploy these values.
NEXT_PUBLIC_SITE_URL=http://localhost:3477
ONBOARDING_ENCRYPTION_KEY=${key}
ONBOARDING_KEY_ID=k1
ONBOARDING_STORE=fs
ONBOARDING_STORE_DIR=./.data/onboarding
ONBOARDING_ACCESS_CODE_HASHES=${hash}
ONBOARDING_SESSION_SECRET=${secret}
ONBOARDING_ADMIN_TOKEN=${token}
ONBOARDING_RETENTION_DAYS=90
ONBOARDING_MAX_UPLOAD_BYTES=4194304
`;
writeFileSync(".env.local", env);
console.log(JSON.stringify({ code, token, storeDir: ".data/onboarding" }, null, 2));
